# Etapa 1: Construcción
#FROM openjdk:20-jdk AS builder
FROM maven:3.9.4-eclipse-temurin-20 AS builder

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el código del proyecto al contenedor
COPY . .

# Construir la aplicación
RUN ./mvnw clean package -DskipTests

# Etapa 2: Ejecución
FROM openjdk:20-jdk

# Establecer el directorio de trabajo para la aplicación
WORKDIR /app

# Copiar el archivo JAR desde la etapa de construcción
COPY --from=builder /app/target/*.jar app.jar

# Exponer el puerto en el que corre la aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]